# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 10005
  servlet:
    context-path: /

#debug: true
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
# 移除自动配置类
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  # Oracle 数据库
  datasource:
    dynamic:
      datasource:
        # ****************************** mysql ******************************
        # MySQL数据库配置
        master:
          driver-class-name: com.mysql.jdbc.Driver #
          url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          username: root
          password: root
        slave:
          driver-class-name: com.mysql.jdbc.Driver #
          url: jdbc:mysql://localhost:3306/nsrep_screen_control?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          username: root
          password: root

  kafka:
    one:
      bootstrap-servers: 10.0.0.12:9092,10.0.0.13:9092,10.0.0.16:9092 #172.18.0.46:9092,172.18.0.47:9092,172.18.0.48:9092 # 10.9.1.199:9092
      listener:
        missing-topics-fatal: false
      consumer:
        auto-offset-reset: latest
        enable-auto-commit: true
        group-id: local-test
      producer:
        max-request-size: 150000

    two:
      bootstrap-servers: 172.18.0.46:9092,172.18.0.47:9092,172.18.0.48:9092
      listener:
        missing-topics-fatal: false
      consumer:
        auto-offset-reset: latest
        enable-auto-commit: true
        group-id: screen-control-local

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL

  redis:
    host: 172.18.100.1
    port: 6379
    password: bc_13579
    database: 15

  rabbitmq:
    host: 47.244.107.125
    port: 5672
    username: guest
    password: guest
    #消息确认配置项
    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true

  quartz:
    job-store-type: jdbc
    initialize-schema: embedded
    #设置自动启动，默认为 true
    auto-startup: true
    #启动时更新己存在的Job
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 60000
            clusterCheckinInterval: 10000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#arthas:
 # agent-id: hsehdfsfghhwertyfad
 # tunnel-server: ws://47.244.107.125:7777/ws

hbase:
  zookeeper:
    # hbase 连接的zookeeper集群，如果集群是使用域名做了映射，需要在本程序所在服务器配置该映射关系
    quorum: 172.18.0.46,172.18.0.47,172.18.0.48
    property:
      # habse 连接的zookeeper集群用的端口
      clientPort: 2181

hdfs:
  path: hdfs://172.18.1.51:8020
  username: hdfs

elasticsearch:
  user:
  password:
  host: 192.168.3.198
  port: 9200

memcache:
  servers: 127.0.0.1:11211
  failover: true
  initConn: 10
  minConn: 2
  maxConn: 1000
  maintSleep: 50
  nagle: false
  socketTO: 3000
  aliveCheck: true






